#!/usr/bin/with-contenv bash
if [ "${NFS_ENABLE:-true}" == "true" ];then
    echo "MOUNTNFS: MOUNTNFS: Starting rpcbind"
    /sbin/rpcbind &
    echo "MOUNTNFS: mount ${NFS_IP:-192.168.3.100}:${NFS_SHARE:-/share/media} ${NFS_MOUNT_POINT:-/downloads}"
    mount ${NFS_IP:-192.168.3.100}:${NFS_SHARE:-/share/media} ${NFS_MOUNT_POINT:-/downloads}
    while [ "$LOOP" != "0" ]; do

        while [[ ! $(mount | grep ${NFS_IP:-192.168.3.100}) ]] || [ ! -f "${NAS_MOUNT_POINT:-/downloads}/MOUNTED" ]; do
            echo "MOUNTNFS: NFS not mounted.  Pausing Transmission."
            transmission-remote -t all --stop

            echo "Unmount and Remount ${NFS_IP:-192.168.3.100}:${NFS_SHARE:-/share/media} on ${NFS_MOUNT_POINT:-/downloads}"
            umount ${NFS_MOUNT_POINT}
            mount ${NFS_IP}:${NFS_SHARE:-/share/media} ${NFS_MOUNT_POINT:-/downloads}

            echo "Resuming transmission"
            transmission-remote -t all --start
        done
        sleep 5
    done
fi
while :;do echo "MOUNTNFS: DISABLED - Set parameters in your .env file"; sleep 1d ;done