version: "2.4"
services:
  transmission-tailscale:
    image: beardedtek/transmission-tailscale:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
      - sys_admin
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=${TAILSCALE_IPV6_DISABLED:-1}  # 0=ipv6 enabled, 1=ipv6 disabled
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=${TAILSCALE_IPV6_FORWARDING:-1}
    environment:
      DOCKER_NETWORK_SUBNET: ${DOCKER_NETWORK_SUBNET:-192.168.251.0/24}
      TAILSCALE_AUTHKEY: ${TAILSCALE_AUTHKEY}
      TAILSCALE_HOSTNAME: sidecar-nefyoung
      TAILSCALE_TAGS: ${TAILSCALE_TAGS}
      TAILSCALE_ADVERTISE_ROUTE: ${TAILSCALE_ADVERTISE_ROUTE}
      # If TAILSCALE_ENABLE and MOUNT_NFS are set to false
      # container functions just as linuxserver.io/transmission does
      TAILSCALE_ENABLE: ${TAILSCALE_ENABLE:-false}
      MOUNT_NFS: ${MOUNT_NFS:-false} 
      NAS_IP: ${NAS_IP} #ip of nfs server
      NAS_SHARE: ${NAS_SHARE} #share path
    command: "/init"


    networks:
      transmission-tailscale:
          ipv4_address: ${TRANSMISSION_IP:-192.168.251.201}

networks:
  transmission-tailscale:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET:-192.168.251.0/24}
          gateway: ${GATEWAY:-192.168.251.254}
